<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="EST8ADS connects the property you are selling with the property you want to buy and builds possible AI-powered property chains.">
  <title>EST8ADS — Property Chain Intelligence</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{ asset('assets/css/vendors/select2.css') }}">
  <link rel="stylesheet" href="{{ asset('est8ads-assets/styles.css') }}">
  <script type="application/ld+json">
  {"@@context":"https://schema.org","@@type":"FAQPage","name":"EST8ADS Frequently Asked Questions","url":"{{ route('est8ads.home') }}#faq","description":"Answers about EST8ADS property chains, Missing Link Ads, AI analysis, agencies, privacy, pricing, fees and transaction risks."}
  </script>
</head>
<body>
  <header class="site-header" id="top">
    <div class="nav-shell">
      <a class="brand" href="{{ route('est8ads.home') }}" aria-label="EST8ADS home"><img src="{{ asset('est8ads-assets/est8ads-logo.svg') }}" alt="EST8ADS logo"></a>
      <nav class="desktop-nav" aria-label="Primary navigation"><a href="#create">Create your move</a><a href="#what">What is EST8ADS?</a><a href="#how">How it works</a><a href="#faq">FAQ</a><a href="{{ route('est8ads.contact') }}">Contact</a></nav>
      <div class="nav-actions"><button class="language-button" type="button" aria-label="Choose language">EN</button><a class="sign-in" href="{{ route('est8ads.login') }}">Sign in</a><a class="primary-small" href="#create">Get started</a></div>
      <button class="menu-button" type="button" aria-label="Open menu" aria-expanded="false"><span></span><span></span><span></span></button>
    </div>
    <div class="mobile-menu" hidden><a href="#create">Create your move</a><a href="#what">What is EST8ADS?</a><a href="#how">How it works</a><a href="#faq">FAQ</a><a href="{{ route('est8ads.contact') }}">Contact</a><a href="{{ route('est8ads.login') }}">Sign in</a></div>
  </header>

  <main>
    <section class="hero section-shell">
      <div class="hero-copy">
        <div class="eyebrow"><span></span> Villa Bit AI Property Chain Intelligence</div>
        <h1>Do not just sell a property. <em>Complete your entire next sell/buy move at once.</em></h1>
        <p class="hero-lead">EST8ADS deeply analyzes the property you want to sell and the property you want to buy, then connects compatible buyers, sellers and properties into potential transaction chains.</p>
        <div class="hero-actions"><a class="button primary" href="#create">Create your property move</a><a class="text-link" href="#how">See how the chain works <span>→</span></a></div>
        <div class="trust-row"><div class="stat-badge"><strong>45%</strong><span>of recent U.S. buyers who made a down payment used money from selling their previous home.</span></div><p>Source: National Association of Realtors, 2025 Home Buyers and Sellers Generational Trends Report.</p></div>
      </div>
      <div class="hero-visual" aria-label="Property chain illustration">
        <div class="visual-card visual-card-main"><span class="mini-label">YOUR NEXT MOVE</span><h2>Sell one property.<br>Buy the next one.<br><em>At the same time.</em></h2><div class="move-flow"><div class="property-node"><div class="node-icon house-icon"></div><span>Property to sell</span><strong>Your current property</strong></div><div class="ai-node"><span>8</span><small>AI</small></div><div class="property-node"><div class="node-icon key-icon"></div><span>Property to buy</span><strong>Your next property</strong></div></div><div class="chain-status"><span class="pulse"></span> Searching compatible property chains</div></div>
        <div class="floating-card float-one"><span>Potential chain</span><strong>4 connected moves</strong></div><div class="floating-card float-two"><span>Missing link</span><strong>1 property identified</strong></div>
      </div>
    </section>

    <section class="create-section" id="create"><div class="section-shell create-shell">
      <div class="section-intro centered"><span class="section-kicker">GET STARTED</span><h2>Tell us your complete property move</h2><p>Add the property you want to sell and the property you want to buy at the same time. All fields are available here on the first page.</p></div>
      <div class="access-note-grid" aria-label="EST8ADS pricing and agency access"><article class="access-note"><span>PRIVATE &amp; ONE-TIME USERS</span><strong>$12 for 30 days</strong><p>A one-time payment publishes one property move request for 30 days and includes access to EST8ADS AI Server analysis. EST8ADS charges no commission on any property sale.</p></article><article class="access-note agency-access-note"><span>REAL ESTATE AGENCIES USING VILLA BIT AI</span><strong>Unlimited free EST8ADS publishing</strong><p>Agencies using <a href="https://villabit.ai" target="_blank" rel="noopener noreferrer">Villa Bit AI</a> can publish unlimited EST8ADS requests through the fully integrated Villa Bit AI Server.</p></article></div>
      <div class="form-layout">
        <form id="propertyMoveForm" class="move-form" method="POST" action="{{ route('est8ads.moves.store') }}" enctype="multipart/form-data" novalidate>
          <?= csrf_field() ?>
          <div class="form-progress" aria-label="Form sections"><a href="#form-you" class="progress-item active"><span>1</span><b>About you</b></a><a href="#form-sell" class="progress-item"><span>2</span><b>Property to sell</b></a><a href="#form-buy" class="progress-item"><span>3</span><b>Property to buy</b></a><a href="#form-chain" class="progress-item"><span>4</span><b>Chain conditions</b></a><a href="#form-contact" class="progress-item"><span>5</span><b>Contact</b></a></div>
          <section class="form-card" id="form-you" data-form-section="1">
            <div class="form-card-heading"><span class="number">01</span><div><h3>Who is creating this property move?</h3><p>This helps EST8ADS understand how the chain should be handled.</p></div></div>
            <div class="choice-grid three">
              <label class="choice-card"><input type="radio" name="user_type" value="Private buyer or seller"><span class="choice-icon owner-icon"></span><strong>Private buyer or seller</strong><small>I want to sell one property or buy one property without combining both transactions.</small></label>
              <label class="choice-card"><input type="radio" name="user_type" value="Buyer and seller" checked><span class="choice-icon move-icon"></span><strong>Buyer and seller</strong><small>I want to sell one property and buy the next one at the same time.</small></label>
              <label class="choice-card"><input type="radio" name="user_type" value="Real estate agency or agent"><span class="choice-icon agent-icon"></span><strong>Real estate agency or agent</strong><small>I represent an agency or agent. Agencies using Villa Bit AI receive unlimited free EST8ADS publishing through the integrated server.</small></label>
            </div>
            <div class="field-grid two"><label class="field"><span>Move type *</span><select name="move_type" required><option value="">Select the transaction order</option><option>Only sell a property</option><option>Only buy a property</option><option>Sell first, then buy</option><option>Buy first, then sell</option><option selected>Both transactions at the same time</option><option>Open to a direct property exchange</option></select></label><label class="field"><span>Current stage *</span><select name="current_stage" required><option value="">Select current stage</option><option>Planning only</option><option>Property ready to list</option><option>Property already advertised</option><option>Buyer already interested</option><option>Offer received</option><option>Purchase property already found</option></select></label></div>
          </section>
          <section class="form-card sell-card" id="form-sell" data-form-section="2">
            <div class="form-card-heading"><span class="number">02</span><div><h3>Property you want to sell</h3><p>Describe the property whose sale will help finance your next purchase.</p></div></div>
            <div class="field-grid two">
              <label class="field"><span>Listing title *</span><input type="text" name="sell_title" placeholder="Example: Sea-view apartment in Split" required></label><label class="field"><span>Property type *</span><select class="property-type-select" name="sell_type" data-placeholder="Select property type" required>@include('partials.property-type-options', ['selected' => ''])</select></label>
              <label class="field"><span>Country *</span><input type="text" name="sell_country" placeholder="Country" required></label><label class="field"><span>City / area *</span><input type="text" name="sell_city" placeholder="City, district or island" required></label><label class="field full"><span>Address or micro-location</span><input type="text" name="sell_address" placeholder="Street, neighbourhood or a short location description"></label>
              <label class="field"><span>Asking price *</span><div class="input-with-select"><input type="number" name="sell_price" min="0" placeholder="350000" required><select name="sell_currency" aria-label="Currency"><option>EUR</option><option>USD</option><option>GBP</option><option>CHF</option></select></div></label><label class="field"><span>Lowest acceptable price</span><input type="number" name="sell_min_price" min="0" placeholder="Optional"></label>
              <label class="field"><span>Interior size (m²)</span><input type="number" name="sell_size" min="0" placeholder="95"></label><label class="field"><span>Land size (m²)</span><input type="number" name="sell_land_size" min="0" placeholder="Optional"></label><label class="field"><span>Bedrooms</span><input type="number" name="sell_bedrooms" min="0" placeholder="3"></label><label class="field"><span>Bathrooms</span><input type="number" name="sell_bathrooms" min="0" placeholder="2"></label>
              <label class="field"><span>Property condition</span><select name="sell_condition"><option value="">Select condition</option><option>New construction</option><option>Excellent</option><option>Good</option><option>Needs light renovation</option><option>Needs full renovation</option></select></label><label class="field"><span>Ownership status</span><select name="sell_ownership"><option value="">Select ownership status</option><option>Clear ownership</option><option>Mortgage / loan exists</option><option>Co-owned property</option><option>Inheritance process</option><option>Other legal condition</option></select></label>
              <label class="field full"><span>Main property features</span><input type="text" name="sell_features" placeholder="Sea view, pool, garage, elevator, garden, rental income..."></label><label class="field full"><span>Property description *</span><textarea name="sell_description" rows="5" placeholder="Describe the property, its strongest selling points and any important conditions." required></textarea></label><label class="field full"><span>Existing listing URL</span><input type="url" name="sell_url" placeholder="https://..."></label>
              <label class="field full upload-field"><span>Property photos</span><input id="sellPhotos" type="file" name="sell_photos" accept="image/*" multiple><div class="upload-box"><div class="upload-icon">↑</div><strong>Upload or drag property photos here</strong><small>JPG, PNG or WEBP. Multiple files are allowed.</small><em id="photoCount">No files selected</em></div></label>
            </div>
          </section>
          <section class="form-card buy-card" id="form-buy" data-form-section="3">
            <div class="form-card-heading"><span class="number">03</span><div><h3>Property you want to buy</h3><p>Define your next property and the conditions that must be met.</p></div></div>
            <div class="field-grid two">
              <label class="field"><span>Wanted property type *</span><select class="property-type-select" name="buy_type" data-placeholder="Select property type" required>@include('partials.property-type-options', ['selected' => ''])</select></label><label class="field"><span>Preferred country *</span><input type="text" name="buy_country" placeholder="Country" required></label><label class="field"><span>Preferred city / area *</span><input type="text" name="buy_city" placeholder="One or several acceptable locations" required></label>
              <label class="field"><span>Minimum budget</span><input type="number" name="buy_budget_min" min="0" placeholder="250000"></label><label class="field"><span>Maximum budget *</span><div class="input-with-select"><input type="number" name="buy_budget_max" min="0" placeholder="450000" required><select name="buy_currency" aria-label="Currency"><option>EUR</option><option>USD</option><option>GBP</option><option>CHF</option></select></div></label>
              <label class="field"><span>Minimum interior size (m²)</span><input type="number" name="buy_size_min" min="0" placeholder="80"></label><label class="field"><span>Maximum interior size (m²)</span><input type="number" name="buy_size_max" min="0" placeholder="Optional"></label><label class="field"><span>Minimum bedrooms</span><input type="number" name="buy_bedrooms" min="0" placeholder="2"></label><label class="field"><span>Minimum bathrooms</span><input type="number" name="buy_bathrooms" min="0" placeholder="1"></label>
              <label class="field"><span>Acceptable condition</span><select name="buy_condition"><option>Any condition</option><option>New construction only</option><option>Move-in ready</option><option>Light renovation acceptable</option><option>Full renovation acceptable</option></select></label><label class="field"><span>Purchase financing</span><select name="financing"><option>Sale of current property</option><option>Sale proceeds + mortgage</option><option>Mortgage approved</option><option>Cash available</option><option>Other financing</option></select></label>
              <label class="field full"><span>Must-have features</span><input type="text" name="buy_must_have" placeholder="Example: sea view, parking, lift, minimum two bedrooms, quiet area..."></label><label class="field full"><span>Flexible preferences</span><input type="text" name="buy_flexible" placeholder="What could be changed if the right chain solution is found?"></label><label class="field full"><span>Describe your ideal next property *</span><textarea name="buy_description" rows="5" placeholder="Explain what you are looking for and what would make the purchase work for you." required></textarea></label>
            </div>
          </section>
          <section class="form-card chain-card" id="form-chain" data-form-section="4">
            <div class="form-card-heading"><span class="number">04</span><div><h3>Property chain conditions</h3><p>These details help the AI find realistic connected transactions, not only similar listings.</p></div></div>
            <div class="field-grid two"><label class="toggle-field"><input type="checkbox" name="must_sell_first" checked><span class="toggle"></span><span><strong>I must sell before I can buy</strong><small>The purchase depends on funds from my sale.</small></span></label><label class="toggle-field"><input type="checkbox" name="temporary_housing"><span class="toggle"></span><span><strong>Temporary housing is possible</strong><small>I can accept a short gap between transactions.</small></span></label><label class="toggle-field"><input type="checkbox" name="direct_exchange"><span class="toggle"></span><span><strong>I am open to a direct exchange</strong><small>A property swap with a price difference may be considered.</small></span></label><label class="toggle-field"><input type="checkbox" name="price_flexible"><span class="toggle"></span><span><strong>My selling price is flexible</strong><small>I may adjust it when that unlocks the complete move.</small></span></label><label class="field full"><span>Conditions that must be met</span><textarea name="chain_conditions" rows="4" placeholder="Examples: completion date, deposit timing, possession date, legal conditions, minimum net amount after mortgage repayment..."></textarea></label><label class="field full"><span>Additional information for AI chain analysis</span><textarea name="chain_notes" rows="4" placeholder="Add anything that could help EST8ADS understand the complete transaction structure."></textarea></label></div>
          </section>
          <section class="form-card contact-card" id="form-contact" data-form-section="5">
            <div class="form-card-heading"><span class="number">05</span><div><h3>Contact and account details</h3><p>We use these details to save your move and contact you when a compatible chain is identified.</p></div></div>
            <div class="field-grid two"><label class="field"><span>First name *</span><input type="text" name="first_name" autocomplete="given-name" required></label><label class="field"><span>Last name *</span><input type="text" name="last_name" autocomplete="family-name" required></label><label class="field"><span>Email address *</span><input type="email" name="email" autocomplete="email" required></label><label class="field"><span>Phone number *</span><input type="tel" name="phone" autocomplete="tel" placeholder="+385 ..." required></label><label class="field full"><span>Preferred language</span><select name="language"><option>English</option><option>Croatian</option><option>German</option><option>Italian</option><option>Spanish</option><option>Portuguese</option><option>French</option><option>Other</option></select></label><label class="check-line full"><input type="checkbox" name="terms" required><span>I confirm that the information is accurate and I agree to the Terms of Use and Privacy Policy. *</span></label><label class="check-line full"><input type="checkbox" name="service_terms" required><span>I understand that any applicable fee covers publication of my property request and access to the EST8ADS AI Server system. EST8ADS charges no sales commission and does not guarantee a buyer, seller, match, sale, purchase or completed transaction. *</span></label><label class="check-line full"><input type="checkbox" name="agent_contact"><span>Verified real estate agencies may contact me when they have a relevant buyer, seller or property.</span></label></div>
            <div class="form-actions"><button type="button" class="button secondary" id="saveDraft">Save draft</button><button type="submit" class="button primary submit-button">Analyze my property move <span>→</span></button></div><p class="form-note">Each participant keeps their own agent, agreements, fees and control over the transaction. EST8ADS provides property-request publishing and AI analysis only; it does not act as the participant’s broker, legal adviser or transaction guarantor.</p>
          </section>
        </form>
        <aside class="summary-panel" aria-label="Property move summary"><div class="summary-sticky"><div class="summary-header"><span>LIVE MOVE SUMMARY</span><div class="summary-logo">8</div></div><div class="summary-route"><div class="route-item"><span>SELL</span><strong id="summarySell">Your current property</strong><small id="summarySellLocation">Location not added</small></div><div class="route-line"><i></i><b>AI</b><i></i></div><div class="route-item"><span>BUY</span><strong id="summaryBuy">Your next property</strong><small id="summaryBuyLocation">Location not added</small></div></div><div class="summary-metrics"><div><small>Sale price</small><strong id="summarySalePrice">—</strong></div><div><small>Buy budget</small><strong id="summaryBuyPrice">—</strong></div></div><div class="summary-price-box" id="summaryAccessBox"><span id="summaryAccessLabel">PRIVATE / ONE-TIME USER</span><strong id="summaryAccessTitle">$12 for 30 days</strong><p id="summaryAccessText">Includes one property move request and EST8ADS AI Server analysis. No sales commission.</p><a id="summaryAccessLink" href="https://villabit.ai" target="_blank" rel="noopener noreferrer" hidden>Visit Villa Bit AI →</a></div></div></aside>
      </div>
      <aside class="service-disclaimer" aria-label="EST8ADS service and results disclaimer"><span class="section-kicker">IMPORTANT SERVICE INFORMATION</span><h3>Deep AI analysis can reveal opportunities and weak points, but no sale is guaranteed.</h3><div class="service-disclaimer-grid"><p><strong>What the fee covers.</strong> For private persons and one-time users, the one-time $12 fee covers publication of one property move request for 30 days and access to the EST8ADS AI Server system. EST8ADS does not request or receive any commission from a real estate sale.</p><p><strong>What the AI does.</strong> EST8ADS uses deep AI analysis to search for compatible buyers, sellers, properties and transaction conditions. It attempts to connect property requests into potential chain sales and may identify weak, blocked or stalled points that could be preventing a property transaction from moving forward.</p><p><strong>No guaranteed result.</strong> AI analysis may produce useful matches, insights or sales opportunities, but EST8ADS does not guarantee a buyer, seller, property match, sale, purchase, transaction completion, selling price, timing or financial result.</p><p><strong>Your responsibility.</strong> Every participant remains responsible for their own real estate agent, legal and tax advice, due diligence, contracts, fees and final transaction decisions.</p></div></aside>
    </div></section>

    <section class="statement-section"><div class="section-shell statement-grid"><div class="statement-number">45%</div><div class="statement-copy"><h2>A large share of real estate sales is connected with plans to buy the next property using money from an existing one.</h2><p>If you are selling your own property and want to use that money to buy your next one, you are not dealing with only one transaction. You are dealing with two connected transactions at the same time.</p><p>For you, there is much more value when the sale of your current property and the purchase of your next property are handled at the same time. The main focus is not only selling your property. The main focus is completing your entire next move.</p></div></div></section>

    <section class="content-section section-shell" id="what"><div class="section-intro split-intro"><div><span class="section-kicker">PROPERTY CHAIN INTELLIGENCE</span><h2>What is EST8ADS?</h2></div><p>EST8ADS is a Property Chain Intelligence platform based on Villa Bit AI technology, built for private buyers, sellers and real estate agents. Private and one-time users can publish one property move request for 30 days for $12, while real estate agencies using Villa Bit AI receive unlimited free EST8ADS publishing through the fully integrated Villa Bit AI Server.</p></div><div class="feature-grid"><article class="feature-card featured"><div class="feature-visual chain-visual"><div class="chain-dot one"></div><div class="chain-dot two"></div><div class="chain-dot three"></div><div class="chain-dot four"></div><div class="chain-center">8</div></div><h3>Connect complete property moves</h3><p>Our AI technology connects compatible property moves into potential transaction chains. EST8ADS works with a minimum of two connected transactions at the same time: selling one property and buying the next one, or the reverse.</p></article><article class="feature-card"><div class="feature-number">01</div><h3>More than one transaction</h3><p>Property chains are often much larger. Through deep AI analysis, Villa Bit AI can connect multiple sales and purchases at the same time as one complete property chain.</p></article><article class="feature-card"><div class="feature-number">02</div><h3>Identify the missing link</h3><p>EST8ADS can identify the specific buyer, seller, property or condition that is preventing the entire chain from moving forward.</p></article><article class="feature-card wide"><div class="missing-link-graphic"><span>SALE</span><i></i><span>PURCHASE</span><i class="broken"></i><b>?</b><i></i><span>SALE</span></div><div><h3>One ordinary property may unlock several sales</h3><p>EST8ADS gives real estate agencies valuable information about which property should be advertised more strongly or receive more sales effort. That one property may be much more valuable than it first appears because one successful move can unlock multiple sales further down the chain.</p></div></article></div></section>

    <section class="how-section" id="how"><div class="section-shell"><div class="section-intro centered light-text"><span class="section-kicker">HOW A PROPERTY CHAIN WORKS</span><h2>One complete solution instead of separate waiting</h2><p>EST8ADS analyzes the complete transaction structure for you on a more advanced, algorithm-based level.</p></div><div class="steps"><article class="step-card"><span class="step-number">01</span><h3>Tell us your next move</h3><p>Add at the same time the property you want to sell and the property you want to buy, including your price range, preferred location, timing and any conditions that must be met.</p></article><article class="step-card"><span class="step-number">02</span><h3>We build possible property chains</h3><p>EST8ADS compares your buying and selling requests using advanced AI technology. It analyzes compatible buyers, sellers and properties to identify direct matches and build connected property chain transactions.</p></article><article class="step-card"><span class="step-number">03</span><h3>We find the complete solution or missing link</h3><p>Villa Bit AI Property Chain Intelligence finds a matching buyer or seller for you at the same time. If the chain cannot move forward, it identifies the one missing property, buyer, seller or condition that could unlock the greatest number of sales.</p></article><article class="step-card"><span class="step-number">04</span><h3>Unlock multiple sales</h3><p>When the complete solution or the missing link is found, several connected property transactions may be able to move forward. Each participant keeps their own agent, agreements, fees and control over their transaction.</p></article></div></div></section>

    <?php
      $faqGroups = [
        ['01','General',[
          ['What is EST8ADS?','EST8ADS is a Property Chain Intelligence platform based on Villa Bit AI technology. It connects compatible buying and selling intentions, identifies the missing property, buyer, seller or condition preventing several transactions from moving forward, and can create focused Missing Link Ads.'],
          ['Is EST8ADS a normal property portal?','No. Traditional portals mainly display individual properties for sale or rent. EST8ADS analyzes the relationships and dependencies between buyers, sellers, properties, financing, timing and transaction conditions.'],
          ['What is a property chain?','A property chain is a sequence of connected transactions in which one person may need to sell before buying, while another participant may be in the same position. One completed transaction may depend on several others.'],
          ['What is a Missing Link?','A Missing Link is the property, buyer, seller, financing approval, timing agreement, verification or other condition preventing a possible chain from progressing.'],
          ['What is a Missing Link Ad?','A Missing Link Ad is a focused public request created to find the exact missing property or participant capable of unlocking one or more connected transactions. Instead of advertising every property in a chain, it focuses attention on the one opportunity that matters most.'],
          ['Who can use EST8ADS?','EST8ADS is built for private buyers, sellers, people who need to sell before buying, real estate agents and agencies, developers, advisers and other professionals connected to a property move.'],
        ]],
        ['02','Buyers and sellers',[
          ['Can I join if I only want to buy?','Yes. A buyer may join without selling a property. Your purchase may become the first or final link needed in an existing chain.'],['Can I join if I only want to sell?','Yes. Your property may already match active buyer demand or become the missing link in a larger chain.'],['Can I join if my property is not publicly listed?','Yes. You may begin with a private or limited property profile and decide later whether to reveal additional information. An off-market or conditionally available property can still be valuable to an active chain.'],['Can I say that I will sell only if I find another property?','Yes. Conditional selling is one of the main situations EST8ADS is designed to support. You can describe both the property you may sell and the replacement property you need.'],['What if I must sell before I can buy?','Enter the property you need to sell and the property you want to buy as one connected move. EST8ADS can then analyze both sides together instead of treating them as unrelated transactions.'],['Does joining a chain obligate me to buy or sell?','No, unless you later enter a separate binding agreement. Joining EST8ADS or appearing in a possible chain does not itself create a purchase contract, sale contract, brokerage agreement or legal obligation to complete.'],['Can I use EST8ADS with my existing agent?','Yes. EST8ADS is designed to work with existing agents and representatives. Each participant can keep their own agent, agreements, fees and control over the transaction.'],['Can one person be part of more than one possible chain?','Yes. EST8ADS may identify several possible paths and rank them according to compatibility, verification and readiness.'],
        ]],
        ['03','AI matching and Missing Links',[
          ['How does EST8ADS build property chains?','The system compares structured buying and selling intentions using factors such as property type, location, price range, financing, timing, essential requirements, transaction dependencies and conditions that must be met.'],['What information does the AI analyze?','EST8ADS may analyze the property you want to sell, the property you want to buy, locations, price ranges, financing status, property requirements, agent involvement, flexibility and practical or legal conditions.'],['What can be a Missing Link?','A Missing Link may be a specific property, a qualified buyer, a willing seller, financing approval, proof of funds, timing alignment, completed verification or another legal or practical condition.'],['What can deeper AI analysis reveal?','Deeper AI analysis may identify compatible buyers, sellers and properties, alternative chain paths, weak points, blocked stages or stalled conditions that may be preventing a property transaction from moving forward.'],['What happens when a missing property or participant is found?','The system reviews the match, updates the possible chain and allows the appropriate participants or their representatives to review a privacy-safe summary and decide whether to continue.'],['What is Chain Confidence?','Chain Confidence is an informational readiness score based on available data, verification, price realism, financing, timing, participant confirmations and unresolved conditions. It is not a guarantee that a transaction will complete.'],['What is the Private Chain Room?','The Private Chain Room is a controlled workspace for reviewing the chain structure, participant status, confirmed properties, missing links, milestones, time limits and approved communications without unnecessarily exposing personal information.'],['Does EST8ADS advertise every property in the chain?','Not necessarily. EST8ADS is designed to identify the smallest missing element capable of unlocking the greatest number of connected transactions and focus public attention on that Missing Link.'],
        ]],
        ['04','Agents and agencies',[
          ["Does EST8ADS take over an agent's client?",'No. Client identities, contact details, representation and communication remain controlled according to platform permissions, existing agreements and applicable law.'],['Do agencies have to share commissions?','No. EST8ADS does not require commission sharing. Each agency may retain its own client, agreement, communication and compensation arrangement.'],['Is EST8ADS a real estate agency?','EST8ADS is primarily a technology, advertising, intelligence and coordination platform. Licensed brokerage and other regulated professional services must be provided by appropriately authorized professionals under separate agreements where required.'],['What do agencies using Villa Bit AI receive?','Real estate agencies using Villa Bit AI can publish unlimited EST8ADS property move requests free of charge through the fully integrated Villa Bit AI Server.'],['Where can an agency learn more about Villa Bit AI?','Agencies can visit Villa Bit AI at https://villabit.ai to learn about the integrated AI Server and unlimited EST8ADS publishing access.'],['Can agencies use EST8ADS under their own brand?','Selected agency tools may include white-label intake forms, website widgets, campaign tools, dashboards, team access, analytics and agency-facing interfaces.'],['How can EST8ADS help an agency move more transactions forward?','EST8ADS can help identify whether a deal is blocked by a missing property, buyer, financing issue, timing conflict or unverified participant. One client who must both sell and buy may also connect the agency to more than one transaction.'],
        ]],
        ['05','Privacy and verification',[
          ['Will my name and contact details be public?','No. Public Missing Link Ads use privacy-safe information. Personal contact details are not automatically published or released to everyone in a possible chain.'],['What information may be shown publicly?','A public ad may show the required property type, general location, budget range, verification level, number of connected transactions, estimated chain value, target timeline and a privacy-safe summary.'],['Why is verification needed?','Verification helps distinguish genuine transaction-ready participants from casual or inaccurate enquiries and improves the quality of matching and chain analysis.'],['What does Chain Ready mean?','Chain Ready means that a participant has completed the required verification level, confirmed the main conditions and indicated a willingness to proceed if a suitable chain is completed.'],['Does verification guarantee ownership, funds or legal status?','No. Verification indicates that specific information or documents were reviewed according to the platform process. It is not a substitute for formal legal, financial, title, valuation, inspection or due-diligence work.'],['How are responses to a Missing Link Ad reviewed?','A person responding to an ad does not automatically receive private participant details. EST8ADS first checks whether the property, buyer or seller is relevant before an approved privacy-safe match summary is shared.'],
        ]],
        ['06','Pricing, fees and results',[
          ['How much does EST8ADS cost for a private or one-time user?','A private person or one-time user pays $12 to publish one property move request for 30 days and receive access to EST8ADS AI Server analysis.'],['What does the $12 fee cover?','The fee covers publication of one property move request for 30 days and use of the EST8ADS AI Server system for deeper property-chain analysis. It is a technology and advertising service fee.'],['Is the $12 fee a real estate commission?','No. EST8ADS does not request or receive a commission from a property sale. The fee is for publishing the request and using the AI Server system.'],['How long does one private request stay active?','One private or one-time property move request stays active for 30 days. A new payment or plan may be required to continue after that period.'],['Is EST8ADS free for real estate agencies?','Real estate agencies using Villa Bit AI receive unlimited free EST8ADS publishing through the integrated Villa Bit AI Server. Other agency services or plans may have separate terms.'],['Does EST8ADS guarantee a buyer, seller or completed sale?','No. EST8ADS provides matching, deeper AI analytics, advertising and coordination tools, but it does not guarantee a buyer, seller, property match, sale, purchase, selling price, timing, financing or completed transaction.'],['What results can the AI analysis provide?','The AI may identify useful matches, potential chains, sales opportunities, weak points, blocked conditions or stalled stages. These insights may help a transaction move forward, but every result remains conditional.'],['Are professional brokerage, legal and financial services included?','No. Real estate brokerage, legal, tax, valuation, inspection, financing, notarial, escrow and closing services may be regulated and must be provided by appropriately licensed or authorized professionals under separate agreements where required.'],['Who is responsible for due diligence and final decisions?','Every participant remains responsible for their own agent, legal and tax advice, inspections, valuation, due diligence, contracts, professional fees and final transaction decisions.'],['Are chain counts, readiness scores and estimated values guaranteed?','No. Chain counts, readiness scores, estimated values, matches and projected outcomes are informational and may change as participant data, market conditions, verification and transaction requirements change.'],
        ]],
      ];
      $faqIds = ['faq-general','faq-buyers-sellers','faq-ai-matching','faq-agents','faq-privacy','faq-fees'];
    ?>
    <section class="faq-section" id="faq"><div class="section-shell"><div class="section-intro centered faq-intro"><span class="section-kicker">EST8ADS FAQ</span><h2>Frequently asked questions</h2><p>Clear answers about property chains, Missing Link Ads, AI analysis, agencies, privacy, pricing, fees and transaction risks.</p></div><div class="faq-layout"><aside class="faq-category-nav" aria-label="FAQ categories"><strong>FAQ categories</strong><a href="#faq-general">General</a><a href="#faq-buyers-sellers">Buyers and sellers</a><a href="#faq-ai-matching">AI matching and Missing Links</a><a href="#faq-agents">Agents and agencies</a><a href="#faq-privacy">Privacy and verification</a><a href="#faq-fees">Pricing, fees and results</a><a class="faq-start-link" href="#create">Start your property move →</a></aside><div class="faq-content">
      <?php foreach ($faqGroups as $groupIndex => $group): ?>
        <section class="faq-group" id="{{ $faqIds[$groupIndex] }}"><div class="faq-group-heading"><span>{{ $group[0] }}</span><h3>{{ $group[1] }}</h3></div><div class="faq-list">
          <?php foreach ($group[2] as $itemIndex => $item): ?><details class="faq-item"{{ $groupIndex === 0 && $itemIndex === 0 ? ' open' : '' }}><summary>{{ $item[0] }}</summary><div class="faq-answer"><p>{{ $item[1] }}</p></div></details><?php endforeach; ?>
        </div></section>
      <?php endforeach; ?>
    </div></div><div class="faq-disclaimer"><span class="section-kicker">IMPORTANT</span><h3>EST8ADS provides technology, advertising, intelligence and coordination—not guaranteed transaction results.</h3><p>Matches, chain counts, readiness scores, estimated values and projected outcomes are informational. Appropriate licensed professionals must provide regulated brokerage, legal, tax, financial, valuation, inspection, notarial, escrow and closing services where required.</p></div></div></section>

    <section class="final-cta" id="signin"><div class="section-shell final-cta-inner"><h2>Move beyond the old way of placing an ad and waiting.</h2><p>Let EST8ADS analyze your complete transaction structure and find the connected move that can unlock your next property.</p><div class="hero-actions center-actions"><a class="button primary" href="#create">Get started</a><a class="text-link" href="{{ route('est8ads.login') }}">Already have an account? Sign in</a></div></div></section>
  </main>
  <footer class="site-footer"><div class="section-shell footer-grid"><div><p>Property Chain Intelligence based on Villa Bit AI technology.</p></div><div><h4>Platform</h4><a href="#create">Create your move</a><a href="#what">What is EST8ADS?</a><a href="#how">How it works</a><a href="#faq">FAQ</a></div><div><h4>For users</h4><a href="#">Private buyers and sellers</a><a href="#">Real estate agents</a><a href="{{ route('est8ads.login') }}">Sign in</a></div><div><h4>Legal</h4><a href="{{ route('est8ads.privacy') }}">Privacy Policy</a><a href="{{ route('est8ads.terms') }}">Terms of Use</a><a href="{{ route('est8ads.contact') }}">Contact</a></div></div><div class="section-shell footer-bottom"><span>© 2026 EST8ADS. All rights reserved.</span><span>Powered by Villa Bit AI</span></div></footer>
  <div class="toast" id="toast" role="status" aria-live="polite"></div><div class="modal-backdrop" id="successModal" hidden><div class="success-modal" role="dialog" aria-modal="true" aria-labelledby="successTitle"><button class="modal-close" type="button" aria-label="Close">×</button><div class="success-icon">✓</div><span class="section-kicker">PROPERTY MOVE PREPARED</span><h2 id="successTitle">Your complete move is ready for AI analysis.</h2><p>Your property move will be saved securely and submitted to the EST8ADS matching process.</p><button class="button primary modal-close-button" type="button">Continue editing</button></div></div>
  <script src="{{ asset('assets/js/jquery.min.js') }}"></script>
  <script src="{{ asset('assets/js/select2/select2.full.min.js') }}"></script>
  <script src="{{ asset('est8ads-assets/app.js') }}"></script>
</body>
</html>
