<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class VillaReadyPropertyContent extends Model
{
    use HasFactory;

    protected $table = 'villa_ready_property_content';

    protected $fillable = [
        'villa_ready_property_id',
        'content_locked',
        'content_lock_level',
        'hero_eyebrow',
        'hero_chips',
        'hero_media_label',
        'hero_360_url',
        'location_value_title',
        'location_value_subtitle',
        'location_value_content',
        'location_value_highlight',
        'chain_title',
        'chain_subtitle',
        'chain_content',
        'sea_title',
        'sea_subtitle',
        'sea_description',
        'map_title',
        'map_subtitle',
        'map_description',
        'map_embed_url',
        'map_coordinates',
        'stat_total_area',
        'stat_plots',
        'stat_villas',
        'stat_apartments',
        'total_area_m2',
        'plots_count',
        'access_title',
        'access_subtitle',
        'access_intro',
        'access_cards',
        'plots_title',
        'plots_subtitle',
        'plot_sizes',
        'concept_title',
        'concept_subtitle',
        'concept_disclaimer',
        'aerial_title',
        'aerial_subtitle',
        'pricing_title',
        'pricing_subtitle',
        'pricing_payment_text',
        'pricing_discount_text',
        'apartment_discount',
        'villa_discount',
        'custom_villa_option',
        'permitted_structure',
        'basement_use',
        'pricing_currency',
        'buildings_data',
        'total_project_price',
        'tax_title',
        'tax_subtitle',
        'tax_intro',
        'non_eu_note',
        'vat_rate',
        'tax_groups',
        'investor_title',
        'investor_subtitle',
        'investor_content',
        'investor_button',
        'investor_booking_url',
        'investor_whatsapp',
        'investor_email',
        'core_title',
        'core_subtitle',
        'core_values',
        'summary_title',
        'summary_subtitle',
        'summary_text',
        'history_title',
        'history_subtitle',
        'history_content',
        'final_message',
        'contact_form_title',
        'contact_form_subtitle',
        'contact_button',
        'contact_action',
        'agency_recipient_email',
        'agency_phone',
        'crm_pipeline',
        'contact_interest_options',
        'require_name',
        'require_email',
        'require_phone',
        'sidebar_price_label',
        'sidebar_price_value',
        'sidebar_price_note',
        'key_facts',
        'canonical_url',
        'og_image',
        'schema_name',
        'schema_address',
        'schema_latitude',
        'schema_longitude',
        'date_published',
        'date_modified',
        'schema_extra',
        'logo_path',
        'decor_lines_path',
        'decor_dot_path',
    ];

    protected $casts = [
        'content_locked' => 'boolean',
        'require_name' => 'boolean',
        'require_email' => 'boolean',
        'require_phone' => 'boolean',
        'total_project_price' => 'decimal:2',
        'hero_chips' => 'array',
        'access_cards' => 'array',
        'plot_sizes' => 'array',
        'buildings_data' => 'array',
        'tax_groups' => 'array',
        'core_values' => 'array',
        'key_facts' => 'array',
        'date_published' => 'date',
        'date_modified' => 'date',
    ];

    public function property(): BelongsTo
    {
        return $this->belongsTo(VillaReadyProperty::class, 'villa_ready_property_id');
    }
}
